apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: baljitsingh06/backend:1.0
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: task-platform
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001