apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-platform

data:
  PORT: "3001"
  NODE_ENV: production
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CLIENT_URL: http://client.task-platform.svc.cluster.local:3000